[pytest]
pythonpath = src test
testpaths = test

log_cli=true
log_cli_level = DEBUG
log_cli_date_format = %Y-%m-%d %H:%M:%S
log_cli_format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
log_level=INFO
addopts = -s --color=yes --durations=0


asyncio_mode = auto
asyncio_default_fixture_loop_scope = function